import type { CrudColumn, CrudField, CrudOption } from '@/types/crud';
import type { LucideIcon } from 'lucide-vue-next';
import {
    BookOpen,
    Building,
    Building2,
    CalendarClock,
    CalendarDays,
    CalendarRange,
    ClipboardList,
    Database,
    DoorOpen,
    GraduationCap,
    Layers,
    LayoutGrid,
    Megaphone,
    Network,
    School,
    Settings,
    Wallet,
} from 'lucide-vue-next';

export interface FoundationModule {
    key: string;
    path: string;
    title: string;
    description: string;
    resource: string;
    columns: CrudColumn[];
    fields: CrudField[];
    optionSources?: Record<string, string>;
    singularLabel: string;
    icon: LucideIcon;
    searchable?: boolean;
}

const CALENDAR_TYPES: CrudOption[] = [
    { value: 'three-term', label: 'Three-Term' },
    { value: 'quarterly', label: 'Quarterly' },
    { value: 'semester', label: 'Semester' },
    { value: 'trimester', label: 'Trimester' },
    { value: 'custom', label: 'Custom' },
];

const EDUCATION_LEVELS: CrudOption[] = [
    { value: 'primary', label: 'Primary' },
    { value: 'junior-high', label: 'Junior High School' },
    { value: 'senior-high', label: 'Senior High School' },
    { value: 'integrated', label: 'Integrated' },
];

const CALENDAR_CATEGORIES: CrudOption[] = [
    { value: 'holiday', label: 'Holiday' },
    { value: 'enrollment', label: 'Enrollment' },
    { value: 'examination', label: 'Examination' },
    { value: 'school-event', label: 'School Event' },
    { value: 'announcement', label: 'Announcement' },
    { value: 'suspension', label: 'Suspension' },
];

const MASTER_DATA_TYPES: CrudOption[] = [
    { value: 'religion', label: 'Religions' },
    { value: 'nationality', label: 'Nationalities' },
    { value: 'citizenship', label: 'Citizenships' },
    { value: 'ethnicity', label: 'Ethnicities' },
    { value: 'mother-tongue', label: 'Mother Tongues' },
    { value: 'relationship-type', label: 'Relationship Types' },
    { value: 'medical-condition', label: 'Medical Conditions' },
    { value: 'hospital', label: 'Hospitals' },
    { value: 'enrollment-status', label: 'Enrollment Statuses' },
    { value: 'payment-status', label: 'Payment Statuses' },
    { value: 'student-status', label: 'Student Statuses' },
];

const PRIORITIES: CrudOption[] = [
    { value: 'low', label: 'Low' },
    { value: 'normal', label: 'Normal' },
    { value: 'high', label: 'High' },
    { value: 'urgent', label: 'Urgent' },
];

const GENDERS: CrudOption[] = [
    { value: 'male', label: 'Male' },
    { value: 'female', label: 'Female' },
];

const ENROLLMENT_TYPES: CrudOption[] = [
    { value: 'new-student', label: 'New Student' },
    { value: 'continuing', label: 'Continuing' },
    { value: 'returning', label: 'Returning' },
    { value: 'transferee', label: 'Transferee' },
    { value: 're-enrollee', label: 'Re-Enrollee' },
];

const currency = (value: unknown): string => {
    const amount = Number(value) || 0;

    return `₱${amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

export const FOUNDATION_MODULES: FoundationModule[] = [
    {
        key: 'system-settings',
        path: '/system/settings',
        title: 'System Settings',
        description: 'Platform-wide configuration keys used by the whole system.',
        resource: 'system-settings',
        singularLabel: 'system setting',
        icon: Settings,
        columns: [
            { key: 'group', label: 'Group', sortable: true },
            { key: 'key', label: 'Key' },
            { key: 'value', label: 'Value' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'group', label: 'Group', type: 'text', required: true, placeholder: 'e.g. general' },
            { name: 'key', label: 'Key', type: 'text', required: true, placeholder: 'e.g. school.name' },
            { name: 'value', label: 'Value', type: 'textarea', fullWidth: true, placeholder: 'Setting value' },
            { name: 'type', label: 'Type', type: 'text', required: true, placeholder: 'string, boolean, integer…' },
            { name: 'sort_order', label: 'Sort order', type: 'number' },
            { name: 'is_public', label: 'Public', type: 'switch', hint: 'Expose this setting to non-admin roles.' },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
    },
    {
        key: 'school-profile',
        path: '/school/profile',
        title: 'School Profile',
        description: 'Basic information about your school.',
        resource: 'school-profiles',
        singularLabel: 'school profile',
        icon: School,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'short_name', label: 'Short name' },
            { key: 'school_id', label: 'School ID' },
            { key: 'region', label: 'Region' },
            { key: 'is_primary', label: 'Primary', align: 'center' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'name', label: 'School name', type: 'text', required: true, placeholder: 'e.g. Baguio Patriotic High School' },
            { name: 'short_name', label: 'Short name', type: 'text', placeholder: 'e.g. BPHS' },
            { name: 'school_id', label: 'School ID', type: 'text', placeholder: 'e.g. 300001' },
            { name: 'region', label: 'Region', type: 'text' },
            { name: 'division', label: 'Division', type: 'text' },
            { name: 'district', label: 'District', type: 'text' },
            { name: 'address', label: 'Address', type: 'textarea', fullWidth: true },
            { name: 'contact_number', label: 'Contact number', type: 'text' },
            { name: 'email', label: 'Email', type: 'email' },
            { name: 'website', label: 'Website', type: 'url' },
            { name: 'motto', label: 'Motto', type: 'text' },
            { name: 'principal_name', label: 'Principal', type: 'text' },
            { name: 'logo_path', label: 'Logo path', type: 'text', fullWidth: true },
            { name: 'is_primary', label: 'Primary profile', type: 'switch', hint: 'Only one primary school profile is allowed.' },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
    },
    {
        key: 'campuses',
        path: '/school/campuses',
        title: 'Campuses',
        description: 'Physical campuses (main, annex) belonging to the school.',
        resource: 'campuses',
        singularLabel: 'campus',
        icon: Building2,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'address', label: 'Address' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'school_profile_id', label: 'School profile', type: 'select', optionsResource: 'school-profiles' },
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Main Campus' },
            { name: 'code', label: 'Code', type: 'text', placeholder: 'e.g. MAIN' },
            { name: 'address', label: 'Address', type: 'textarea', fullWidth: true },
            { name: 'contact_number', label: 'Contact number', type: 'text' },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
        optionSources: { school_profile_id: 'school-profiles' },
    },
    {
        key: 'academic-years',
        path: '/school/academic-years',
        title: 'Academic Years',
        description: 'School years and their calendar structure.',
        resource: 'academic-years',
        singularLabel: 'academic year',
        icon: CalendarRange,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'start_date', label: 'Starts' },
            { key: 'end_date', label: 'Ends' },
            { key: 'calendar_type', label: 'Calendar' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. 2026-2027' },
            { name: 'code', label: 'Code', type: 'text', placeholder: 'e.g. SY2026' },
            { name: 'start_date', label: 'Start date', type: 'date', required: true },
            { name: 'end_date', label: 'End date', type: 'date', required: true },
            { name: 'calendar_type', label: 'Calendar type', type: 'select', options: CALENDAR_TYPES, required: true },
            { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
            { name: 'is_active', label: 'Active', type: 'switch', hint: 'Only one active academic year is allowed.' },
        ],
    },
    {
        key: 'academic-terms',
        path: '/school/academic-terms',
        title: 'Academic Terms',
        description: 'Terms within each academic year.',
        resource: 'academic-terms',
        singularLabel: 'academic term',
        icon: CalendarClock,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'academic_year', label: 'Academic year' },
            { key: 'sequence', label: 'Sequence' },
            { key: 'start_date', label: 'Starts' },
            { key: 'end_date', label: 'Ends' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'academic_year_id', label: 'Academic year', type: 'select', optionsResource: 'academic-years', required: true },
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. First Quarter' },
            { name: 'code', label: 'Code', type: 'text', placeholder: 'e.g. Q1' },
            { name: 'sequence', label: 'Sequence', type: 'number', hint: 'Order of the term within the year.' },
            { name: 'start_date', label: 'Start date', type: 'date', required: true },
            { name: 'end_date', label: 'End date', type: 'date', required: true },
            { name: 'is_active', label: 'Active', type: 'switch', hint: 'Only one active academic term is allowed.' },
        ],
        optionSources: { academic_year_id: 'academic-years' },
    },
    {
        key: 'grade-levels',
        path: '/school/grade-levels',
        title: 'Grade Levels',
        description: 'Year levels offered by the school.',
        resource: 'grade-levels',
        singularLabel: 'grade level',
        icon: Layers,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'short_name', label: 'Short name' },
            { key: 'education_level', label: 'Education level' },
            { key: 'sequence', label: 'Sequence' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Grade 7' },
            { name: 'code', label: 'Code', type: 'text', placeholder: 'e.g. G7' },
            { name: 'short_name', label: 'Short name', type: 'text', placeholder: 'e.g. 7' },
            { name: 'education_level', label: 'Education level', type: 'select', options: EDUCATION_LEVELS, required: true },
            { name: 'sequence', label: 'Sequence', type: 'number' },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
    },
    {
        key: 'sections',
        path: '/school/sections',
        title: 'Sections',
        description: 'Class sections assigned to each grade level.',
        resource: 'sections',
        singularLabel: 'section',
        icon: LayoutGrid,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'grade_level', label: 'Grade level' },
            { key: 'room', label: 'Room' },
            { key: 'max_capacity', label: 'Capacity' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'grade_level_id', label: 'Grade level', type: 'select', optionsResource: 'grade-levels', required: true },
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Diamond' },
            { name: 'code', label: 'Code', type: 'text', placeholder: 'e.g. 7-DIAMOND' },
            { name: 'room_id', label: 'Room', type: 'select', optionsResource: 'rooms' },
            { name: 'max_capacity', label: 'Max capacity', type: 'number' },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
        optionSources: { grade_level_id: 'grade-levels', room_id: 'rooms' },
    },
    {
        key: 'departments',
        path: '/school/departments',
        title: 'Departments',
        description: 'Subject-area and administrative departments.',
        resource: 'departments',
        singularLabel: 'department',
        icon: Network,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'description', label: 'Description' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Science Department' },
            { name: 'code', label: 'Code', type: 'text', placeholder: 'e.g. SCI' },
            { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
    },
    {
        key: 'subjects',
        path: '/school/subjects',
        title: 'Subjects',
        description: 'Subjects offered across departments and grade levels.',
        resource: 'subjects',
        singularLabel: 'subject',
        icon: BookOpen,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'department', label: 'Department' },
            { key: 'grade_level', label: 'Grade level' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Science 7' },
            { name: 'code', label: 'Code', type: 'text', required: true, placeholder: 'e.g. SCI7' },
            { name: 'department_id', label: 'Department', type: 'select', optionsResource: 'departments' },
            { name: 'grade_level_id', label: 'Grade level', type: 'select', optionsResource: 'grade-levels' },
            { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
        optionSources: { department_id: 'departments', grade_level_id: 'grade-levels' },
    },
    {
        key: 'buildings',
        path: '/facilities/buildings',
        title: 'Buildings',
        description: 'Physical buildings in the campus.',
        resource: 'buildings',
        singularLabel: 'building',
        icon: Building,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'description', label: 'Description' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Main Building' },
            { name: 'code', label: 'Code', type: 'text', placeholder: 'e.g. BLD-A' },
            { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
    },
    {
        key: 'rooms',
        path: '/facilities/rooms',
        title: 'Rooms',
        description: 'Classrooms, laboratories and other rooms.',
        resource: 'rooms',
        singularLabel: 'room',
        icon: DoorOpen,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'building', label: 'Building' },
            { key: 'room_type', label: 'Type' },
            { key: 'capacity', label: 'Capacity' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Room 101' },
            { name: 'code', label: 'Code', type: 'text', placeholder: 'e.g. R101' },
            { name: 'building_id', label: 'Building', type: 'select', optionsResource: 'buildings' },
            { name: 'room_type', label: 'Room type', type: 'text', required: true, placeholder: 'e.g. classroom, laboratory' },
            { name: 'capacity', label: 'Capacity', type: 'number' },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
        optionSources: { building_id: 'buildings' },
    },
    {
        key: 'school-calendar',
        path: '/calendar',
        title: 'School Calendar',
        description: 'Holidays, examinations, enrollment windows and school events.',
        resource: 'school-calendar',
        singularLabel: 'calendar event',
        icon: CalendarDays,
        columns: [
            { key: 'title', label: 'Title', sortable: true },
            { key: 'category', label: 'Category' },
            { key: 'academic_year', label: 'Academic year' },
            { key: 'start_date', label: 'Starts' },
            { key: 'end_date', label: 'Ends' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'title', label: 'Title', type: 'text', required: true, placeholder: 'e.g. Panagbenga Festival' },
            { name: 'category', label: 'Category', type: 'select', options: CALENDAR_CATEGORIES, required: true },
            { name: 'academic_year_id', label: 'Academic year', type: 'select', optionsResource: 'academic-years' },
            { name: 'start_date', label: 'Start date', type: 'date', required: true },
            { name: 'end_date', label: 'End date', type: 'date' },
            { name: 'all_day', label: 'All day', type: 'switch' },
            { name: 'start_time', label: 'Start time', type: 'text', placeholder: 'HH:MM' },
            { name: 'end_time', label: 'End time', type: 'text', placeholder: 'HH:MM' },
            { name: 'location', label: 'Location', type: 'text' },
            { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
        optionSources: { academic_year_id: 'academic-years' },
    },
    {
        key: 'announcements',
        path: '/announcements',
        title: 'Announcements',
        description: 'School-wide announcements and notices.',
        resource: 'announcements',
        singularLabel: 'announcement',
        icon: Megaphone,
        columns: [
            { key: 'title', label: 'Title', sortable: true },
            { key: 'category', label: 'Category' },
            { key: 'priority', label: 'Priority' },
            { key: 'published', label: 'Published', align: 'center' },
            { key: 'published_at', label: 'Published at' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'title', label: 'Title', type: 'text', required: true, placeholder: 'e.g. Midterm Exam Schedule' },
            { name: 'content', label: 'Content', type: 'textarea', fullWidth: true, required: true },
            { name: 'category', label: 'Category', type: 'text', placeholder: 'e.g. academics, events' },
            { name: 'priority', label: 'Priority', type: 'select', options: PRIORITIES },
            { name: 'target_audience', label: 'Target audience', type: 'text', placeholder: 'e.g. all, students, teachers' },
            { name: 'starts_at', label: 'Starts at', type: 'date' },
            { name: 'ends_at', label: 'Ends at', type: 'date' },
            { name: 'published', label: 'Published', type: 'switch', hint: 'Publishing stamps the published date automatically.' },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
    },
    {
        key: 'master-data',
        path: '/system/master-data',
        title: 'Master Data',
        description: 'Reference lists used across modules (religions, statuses, etc.).',
        resource: 'master-data',
        singularLabel: 'master data entry',
        icon: Database,
        columns: [
            { key: 'name', label: 'Name', sortable: true },
            { key: 'code', label: 'Code' },
            { key: 'type', label: 'List' },
            { key: 'is_system', label: 'System', align: 'center' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'type', label: 'List', type: 'select', options: MASTER_DATA_TYPES, required: true },
            { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. Roman Catholic' },
            { name: 'code', label: 'Code', type: 'text', placeholder: 'e.g. RC' },
            { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
            { name: 'sort_order', label: 'Sort order', type: 'number' },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
    },
    {
        key: 'students',
        path: '/school/students',
        title: 'Students',
        description: 'Student records, identities, contact and emergency details.',
        resource: 'students',
        singularLabel: 'student',
        icon: GraduationCap,
        columns: [
            { key: 'student_number', label: 'Student #', sortable: true },
            { key: 'name', label: 'Student', sortable: true },
            { key: 'gender', label: 'Gender' },
            { key: 'birth_date', label: 'Birth date' },
            { key: 'status', label: 'Status' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'first_name', label: 'First name', type: 'text', required: true },
            { name: 'middle_name', label: 'Middle name', type: 'text' },
            { name: 'last_name', label: 'Last name', type: 'text', required: true },
            { name: 'extension_name', label: 'Extension', type: 'text', placeholder: 'e.g. Jr., III' },
            { name: 'nickname', label: 'Nickname', type: 'text' },
            { name: 'gender', label: 'Gender', type: 'select', options: GENDERS, required: true },
            { name: 'birth_date', label: 'Birth date', type: 'date', required: true },
            { name: 'student_number', label: 'Student number', type: 'text' },
            { name: 'lrn', label: 'LRN', type: 'text', placeholder: '12-digit learner reference number' },
            { name: 'school_student_id', label: 'School student ID', type: 'text' },
            { name: 'rfid_number', label: 'RFID number', type: 'text' },
            { name: 'mobile_number', label: 'Mobile number', type: 'text' },
            { name: 'email', label: 'Email', type: 'email' },
            { name: 'status', label: 'Status', type: 'text', placeholder: 'e.g. enrolled, inactive' },
            { name: 'current_address', label: 'Current address', type: 'textarea', fullWidth: true },
            { name: 'permanent_address', label: 'Permanent address', type: 'textarea', fullWidth: true },
            { name: 'emergency_contact_name', label: 'Emergency contact', type: 'text' },
            { name: 'emergency_contact_relationship', label: 'Emergency contact relationship', type: 'text' },
            { name: 'emergency_contact_mobile', label: 'Emergency contact mobile', type: 'text' },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
    },
    {
        key: 'enrollments',
        path: '/school/enrollments',
        title: 'Enrollment Data',
        description: 'Student enrollment records across academic years.',
        resource: 'enrollments',
        singularLabel: 'enrollment',
        icon: ClipboardList,
        columns: [
            { key: 'enrollment_number', label: 'Enrollment #', sortable: true },
            { key: 'student', label: 'Student' },
            { key: 'academic_year', label: 'Academic year' },
            { key: 'grade_level', label: 'Grade level' },
            { key: 'section', label: 'Section' },
            { key: 'enrollment_type', label: 'Type' },
            { key: 'status', label: 'Status' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'student_id', label: 'Student', type: 'select', optionsResource: 'students', optionsLabelKey: 'name', required: true },
            { name: 'academic_year_id', label: 'Academic year', type: 'select', optionsResource: 'academic-years', required: true },
            { name: 'campus_id', label: 'Campus', type: 'select', optionsResource: 'campuses', required: true },
            { name: 'grade_level_id', label: 'Grade level', type: 'select', optionsResource: 'grade-levels', required: true },
            { name: 'section_id', label: 'Section', type: 'select', optionsResource: 'sections' },
            { name: 'enrollment_type', label: 'Enrollment type', type: 'select', options: ENROLLMENT_TYPES, required: true },
            { name: 'enrollment_date', label: 'Enrollment date', type: 'date' },
            { name: 'payment_status', label: 'Payment status', type: 'text', placeholder: 'e.g. unpaid, partial, paid' },
            { name: 'down_payment', label: 'Down payment', type: 'number' },
            { name: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
        optionSources: {
            student_id: 'students',
            academic_year_id: 'academic-years',
            campus_id: 'campuses',
            grade_level_id: 'grade-levels',
            section_id: 'sections',
        },
    },
    {
        key: 'tuitions',
        path: '/school/tuitions',
        title: 'Tuition Data',
        description: 'Per-student tuition, fees, payments and balances.',
        resource: 'tuitions',
        singularLabel: 'tuition record',
        icon: Wallet,
        columns: [
            { key: 'reference_number', label: 'Reference', sortable: true },
            { key: 'student', label: 'Student' },
            { key: 'academic_year', label: 'Academic year' },
            { key: 'total', label: 'Total', align: 'right', sortable: true, cell: (row) => currency(row.total) },
            { key: 'amount_paid', label: 'Paid', align: 'right', sortable: true, cell: (row) => currency(row.amount_paid) },
            { key: 'balance', label: 'Balance', align: 'right', sortable: true, cell: (row) => currency(row.balance) },
            { key: 'status', label: 'Status' },
            { key: 'is_active', label: 'Status', align: 'center' },
        ],
        fields: [
            { name: 'student_id', label: 'Student', type: 'select', optionsResource: 'students', optionsLabelKey: 'name', required: true },
            { name: 'academic_year_id', label: 'Academic year', type: 'select', optionsResource: 'academic-years', required: true },
            { name: 'tuition_fee', label: 'Tuition fee', type: 'number', hint: 'Total and balance are computed automatically.' },
            { name: 'misc_fee', label: 'Miscellaneous fee', type: 'number' },
            { name: 'other_fees', label: 'Other fees', type: 'number' },
            { name: 'discount', label: 'Discount', type: 'number' },
            { name: 'amount_paid', label: 'Amount paid', type: 'number' },
            { name: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
            { name: 'is_active', label: 'Active', type: 'switch' },
        ],
        optionSources: {
            student_id: 'students',
            academic_year_id: 'academic-years',
        },
    },
];

export const foundationModuleByKey = (key: string): FoundationModule | undefined => FOUNDATION_MODULES.find((module) => module.key === key);
